Repository woowa-techcamp-2021/cashbook-13, pull requests merged in 2021-08, with the labels that each got.

#12 (#5) UI 렌더링 구조
  .gitignore
  client/.eslintrc.js
  client/.gitignore
  client/babel.config.json
  client/package-lock.json
  client/package.json
  client/src/app.js
  client/src/child.js
  client/src/core/Component.js
  client/src/core/Store.js
  client/src/core/createElement.js
  client/src/core/jsx.js
  client/src/core/observer.js
  client/src/core/vm.js
  client/src/index.js
  client/src/index.ts
  client/src/sample/Counter.js
  client/src/sample/List.js
  client/src/sample/One.js
  client/src/sample/Two.js
  client/src/sample/counterStore.js
  client/src/sample/counterVM.js
  client/webpack.config.dev.js
  client/webpack.config.prod.js
  server/.gitignore
  server/package.json
  server/src/middlewares/git-oauth.middleware.ts
  server/src/migrations/category.migration.ts
  server/src/migrations/record.migration.ts
  server/src/models/category.model.ts
  server/src/models/payment.model.ts
  server/src/models/record.model.ts
  server/src/models/user-category.model.ts
  server/src/models/user-payment.model.ts
  server/src/models/user.model.ts
Labels: FE

#23 (#5) view-model 구조 개선
  client/src/core/Store.js
  client/src/core/createElement.js
  client/src/core/vm.js
  client/src/index.js
  client/src/sample/counterStore.js
  client/src/sample/counterVM.js
Labels: FE

#24 (#14) 메인 페이지
  client/src/app.js
  client/src/assets/images/analystic-active.svg
  client/src/assets/images/analystic-default.svg
  client/src/assets/images/arrow-left.svg
  client/src/assets/images/arrow-right.svg
  client/src/assets/images/calendar-active.svg
  client/src/assets/images/calendar-default.svg
  client/src/assets/images/cancel.svg
  client/src/assets/images/list-active.svg
  client/src/assets/images/list-default.svg
  client/src/assets/images/minus.svg
  client/src/assets/images/more.svg
  client/src/assets/images/plus.svg
  client/src/assets/images/save-button-large-active.svg
  client/src/assets/images/save-button-large-default.svg
  client/src/assets/images/save-button-small-active.svg
  client/src/assets/images/save-button-small-default.svg
  client/src/components/ImageButton.js
  client/src/components/InputBar.js
  client/src/components/InputItem.js
  client/src/components/MainHeader.js
  client/src/components/RecordContainer.js
  client/src/components/RecordHeader.js
  client/src/components/RecordList.js
  client/src/components/RecordListHeader.js
  client/src/components/RecordListItem.js
  client/src/pages/main.js
  client/src/style.scss
Labels: FE

#25 (#1) globalStyle 추가, 폴더구조 개선
  client/src/config/globalStyle.scss
  client/src/config/reset.scss
  client/src/public/index.html
  client/src/style.scss
  client/webpack.config.dev.js
  client/webpack.config.prod.js
Labels: FE, Pair

#27 (#13)(#17) 로그인/회원가입
  client/.gitignore
  client/package-lock.json
  client/package.json
  client/src/child.js
  client/src/config/constant.js
  client/src/config/globalStyle.scss
  client/src/config/reset.scss
  client/src/pages/auth/index.js
  client/src/pages/auth/style.scss
  client/src/store/authStore.js
  client/src/utils/errorGenerator.js
  client/src/utils/request.js
  client/src/vm/authVM.js
  server/.gitignore
  server/package-lock.json
  server/package.json
  server/src/app.ts
  server/src/config/dotenv.ts
  server/src/controllers/auth.controller.ts
  server/src/errors/http-error.ts
  server/src/errors/service-error.ts
  server/src/middlewares/error.middleware.ts
  server/src/middlewares/wrap-async.ts
  server/src/migrations/user.migration.ts
  server/src/models/user.model.ts
  server/src/routes/auth/index.ts
  server/src/services/jwt.service.ts
  server/src/services/user.service.ts
Labels: BE, FE

#30 (#17) 로그인/회원가입
  server/src/controllers/auth.controller.ts
  server/src/errors/service-error.ts
  server/src/middlewares/checkTokens.ts
  server/src/middlewares/error.middleware.ts
  server/src/migrations/user.migration.ts
  server/src/models/user.model.ts
  server/src/routes/auth/index.ts
  server/src/routes/index.ts
  server/src/services/jwt.service.ts
  server/src/services/user.service.ts
Labels: BE

#32 (#14) 메인 페이지 개발
  client/src/components/Dropdown/index.js
  client/src/components/InputBar/index.js
  client/src/components/Modal/index.js
  client/src/components/Modal/style.scss
  client/src/store/recordStore.js
  client/src/utils/controlModal.js
  client/src/utils/getRecord.js
  client/src/utils/request.js
  client/src/utils/saveRecord.js
  client/src/utils/submitModal.js
  server/src/controllers/category.controller.ts
  server/src/controllers/record.controller.ts
  server/src/controllers/user-category.controller.ts
  server/src/migrations/category.migration.ts
  server/src/migrations/record.migration.ts
  server/src/migrations/user-category.migration.ts
  server/src/routes/category/index.ts
  server/src/routes/index.ts
  server/src/routes/user-category/index.ts
  server/src/services/category.service.ts
  server/src/services/record.service.ts
  server/src/services/user-category.service.ts
Labels: BE, FE
